import { defineConfig } from "vitest/config";

// Root aggregator: runs every package's Vitest project in one process.
// Each package owns its own vitest.config.ts (resolved via the "development"
// export condition so tests run against src, never dist).
export default defineConfig({
  resolve: { conditions: ["development"] },
  test: {
    projects: ["packages/*"],
    coverage: {
      provider: "v8",
      reporter: ["text-summary", "lcov", "json-summary"],
      reportsDirectory: "coverage",
      include: ["packages/*/src/**/*.ts"],
      exclude: [
        // Machine-generated by langium-cli, and committed on purpose.
        "packages/core/src/generated/**",
        // Type declarations carry no statements to cover.
        "**/*.types.ts",
        // Conformance suites are the specification of a port, and they run as
        // part of another package's tests rather than on their own.
        "**/*.suite.ts",
        // Stubs stand in for something a test cannot have, such as the VS Code
        // extension host. They are how other files are covered, not code that
        // ships.
        "**/*.stub.ts",
        "**/index.ts",
        "**/bin/**",
      ],
      thresholds: {
        // A floor that fails the build, not a number to display. Set just under
        // what the suite actually reaches, so ordinary drift does not turn the
        // build red, and raised when the real figure has held above the next
        // step for a while.
        statements: 80,
        branches: 68,
        functions: 80,
        lines: 82,
      },
    },
  },
});
